### ISSUE TITLE
CONTRIBUTING.md should reference signing Adobe CLA as a requirement

### ISSUE THREAD

**Issue by filmaj** [adobe/luaMock#16]
Currently, the link to the CLA is tossed in at the end with no context, just "read more".

We should make it clear that all contributions need to come with a signed CLA (if this has not been done before). A great example of this is [xdm's `CONTRIBUTING.md`'s "How To" list](https://github.com/adobe/xdm/blob/master/CONTRIBUTING.md#how-to-contribute).

Happy to help write up the PR, but I wanted to file the issue first to see what comes out of it.

Cheers!

**Comment by atrifan** [comment]
Hi @filmaj, if you have time to make a PR, in the development branch would be really helpful.

Thanks,
Alex

**Comment by atrifan** [comment]
Thank you so much - it is merged
